language: java
jdk:
- oraclejdk7
notifications:
  email: false
  slack:
    secure: QsKSBkPRyKcrK2ENVvtXynJm+7appUZAYzl9k9M701QlsBZnppQK2igasrcKnD5JvlwRqRrpCQ/PmySTTJWnChBqSxhFbXx1xKkG9SKodJNb1JOhbuCqzxAMw20Vivxgt4O/rVkvBUjw0lAVBqyJ3QSrhGTi2+Q74HLmgiChNKmYNQJF0Z4/02FedCT4C0ekR3djnMzOgiiRKkokH2loX+nODK7AaQqo3oZ67ylPaDVX3P64Zfhp+cKNlxuPV68qbYHFJbLFrppZdCe8f4Ptiw8HW0jjFy1QJ4eDNm9IMi9U44shDk1DEz1ko3+l3PXse4KAMP3C7MkdDw1HFEBJbGWPZZm2IsUeX8IU1nGAoLq9wnX2LsvrSp58irGTrBZhxUSkr1tnXMOuB9tPuAAmSEyca5SXtxx7wKwbOD0MsDLF/dxpOm6VWV4uG6fFKDOwV3AVjsYqL0Nw1jWuWRVLgqTBo4SvgaxJ7sUxximNoJNF26y2+hsrSjQPcRSUKPR4j7xlk3IxfZuIp11bY/XiQNAaOfOL6G24y9ll6alydb4Zs24YxTbXlxBXY23HYmu/CQNWi3JJiOpWOjla4wE+/0uGFk5Tkw0UG7K7Dj+4rqvWF7D+bO/9jv/9jn9dH2ehZuCMORm6132SsjVotDSGlKRGPoDZrcIrCEWfALzKkUI=
branches:
  only:
  - master
after_success:
  - echo "<settings><servers><server><id>conjars.org</id><username>\${env.conjarUser}</username><password>\${env.conjarPassword}</password></server></servers></settings>" > ~/settings.xml
  - mvn deploy --settings ~/settings.xml
