language: java
jdk:
- oraclejdk7
notifications:
  email: false
  slack:
    secure: QsKSBkPRyKcrK2ENVvtXynJm+7appUZAYzl9k9M701QlsBZnppQK2igasrcKnD5JvlwRqRrpCQ/PmySTTJWnChBqSxhFbXx1xKkG9SKodJNb1JOhbuCqzxAMw20Vivxgt4O/rVkvBUjw0lAVBqyJ3QSrhGTi2+Q74HLmgiChNKmYNQJF0Z4/02FedCT4C0ekR3djnMzOgiiRKkokH2loX+nODK7AaQqo3oZ67ylPaDVX3P64Zfhp+cKNlxuPV68qbYHFJbLFrppZdCe8f4Ptiw8HW0jjFy1QJ4eDNm9IMi9U44shDk1DEz1ko3+l3PXse4KAMP3C7MkdDw1HFEBJbGWPZZm2IsUeX8IU1nGAoLq9wnX2LsvrSp58irGTrBZhxUSkr1tnXMOuB9tPuAAmSEyca5SXtxx7wKwbOD0MsDLF/dxpOm6VWV4uG6fFKDOwV3AVjsYqL0Nw1jWuWRVLgqTBo4SvgaxJ7sUxximNoJNF26y2+hsrSjQPcRSUKPR4j7xlk3IxfZuIp11bY/XiQNAaOfOL6G24y9ll6alydb4Zs24YxTbXlxBXY23HYmu/CQNWi3JJiOpWOjla4wE+/0uGFk5Tkw0UG7K7Dj+4rqvWF7D+bO/9jv/9jn9dH2ehZuCMORm6132SsjVotDSGlKRGPoDZrcIrCEWfALzKkUI=
branches:
  only:
  - master
after_success:
  secure: WPdLJnR4DNDLcQpsX22Ch2QNLy2X+MniXJt49zM13Ek1/szEGduA7B/imyt2dCKBY3ljZpH6hHW5qp1ofRq+oN4zDKXdfFxSj9i4Tao/tXN6fETOIBywFy0VIxenkA6jh6WpRzxtTduu4WNiIJmLhwd+UAjcaVresd+OqicpwlsV2oo7TXOXdcsvQssGai4Sc+kUairiTb4AV7VZwabS7wlBTjfbLivZDgc0rLL8UOib19G7obiQOCGRbhPB5pqw+1HfyVL4fa1Z8t2cLRjOBNVS9kylnMUgS2fnIoKauqeBgMgqGJ1w6NwPqDHA94edkcsXJjZPTJ6CXU6ix+S2a7jcoTIaAhJibPqYYWNqSWqoQsIFbQvi67OPiD29eTRyoXTfhI89lAL3KMsStqrD1u7H8lYBw+Oqr/F7gBsnz8bMgnFkEW8DVlLVFfnqQCVs5orxAJBvbqRNQ9ZCDiXIV+3Rp8CthPgbuz2gFN1SL+pzqblOz/QTBJwlWAaxweNn2vR65euXuB1GodXnt2V4aACIpk4OF94s4Fo6YPWjzDawoC/w+nhJTxk8DDM7er2m5GuUspWd1d6q8I2rYp0wEmYOfw6mWyaFAwoPnjV/Jd067thhooneN5muWchQEhgY1i+d6Wv8bKaSmUj892O7b44wZXSyV4fj/meXPTiBdd4=
